name: BUild NW.js apps

on:
  [push, workflow_dispatch]
  
jobs:
  build:
    name: BUild Windows app
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v2
        
      - name: Download NW.js
        run: wget https://dl.nwjs.io/v0.55.0/nwjs-v0.55.0-win-x64.zip
        
      - name: Extract NW.js
        run: unzip nwjs-v0.55.0-win-x64.zip
  build:
    name: Build Linux app
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v2
      
      - name: Download NW.js
        run: wget https://dl.nwjs.io/v0.55.0/nwjs-v0.55.0-linux-x64.tar.gz
        
      - name: Extract NW.js
        run: unzip nwjs-v0.55.0-linux-x64.tar.gz
