name: Build NW.js apps

on:
  [push, workflow_dispatch]
  
jobs:
  build:
    name: Build NW.js apps
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v2
        
      - name: Create build directory and cd to it
        run: mkdir build && cd build
        
      - name: Download Windows NW.js
        run: wget https://dl.nwjs.io/v0.55.0/nwjs-v0.55.0-win-x64.zip
        
      - name: Extract Windows NW.js
        run: unzip nwjs-v0.55.0-win-x64.zip
      
      - name: Download Linux NW.js
        run: wget https://dl.nwjs.io/v0.55.0/nwjs-v0.55.0-linux-x64.tar.gz
        
      - name: Extract Linux NW.js
        run: tar -xvf nwjs-v0.55.0-linux-x64.tar.gz
        
      - name: Delete archives
        run: rm nwjs-v0.55.0-linux-x64.tar.gz nwjs-v0.55.0-win-x64.zip
        
      - name: Rename NW.js directories
        run: mv nwjs-v0.55.0-linux-x64 KitsuneOffline-linux && mv nwjs-v0.55.0-win-x64 KitsuneOffline-win
        
      - name: list files to make sure we are on the right track
        run: echo "Build directory:" && ls -A && echo "Repository:" && ls -A ..
